name: Build and Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Go Release Binary
      uses: ngs/go-release.action@v1.0.2